AWSTemplateFormatVersion: "2010-09-09"

Description: Template for Lambda Sample.

Parameters:
  EnvName:
    Description: Name of an environment. 'dev', 'staging', 'prod' and any name.
    Type: String
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.

  LambdaHandlerPath:
   Description: Path of a Lambda Handler.
      Type: String
    AllowedPattern: ^.*[^0-9]$
    ConstraintDescription: Must end with non-numeric character.

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-role
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Path: /

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub lambda-function-${EnvName}
      Runtime: python3.12
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {'statusCode': 200}
      Handler: !Sub ${LambdaHandlerPath}
      Role: !GetAtt LambdaRole.Arn
